=== engsyst/microservices-examples/validation/src/main/resources/common-xml-examples/datetime.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://it.nure.ua/xmldemo"
        xmlns:tns="http://it.nure.ua/xmldemo" elementFormDefault="qualified">

    <complexType name="DateTime">
        <sequence>
            <element name="Duration" type="duration"/>
            <element name="DateTime" type="dateTime"/>
            <element name="Time" type="time"/>
            <element name="YearMonth" type="gYearMonth"/>
            <element name="MonthDay" type="gMonthDay"/>
            <element name="Year" type="gYear"/>
            <element name="Month" type="gMonth"/>
            <choice minOccurs="0">
                <sequence>
                    <element name="Day" type="gDay" fixed="---14" minOccurs="0" maxOccurs="unbounded"/>
                    <element name="DayOfWeek" type="gDay" fixed="---14" minOccurs="0" maxOccurs="unbounded"/>
                </sequence>
                <sequence minOccurs="0">
                    <element name="Day" type="gDay" fixed="---12" minOccurs="1" maxOccurs="1"/>
                    <element name="DayOfWeek" type="gDay" fixed="---12" minOccurs="0" maxOccurs="unbounded"/>
                </sequence>
            </choice>
        </sequence>
    </complexType>
    <element name="datetime" type="tns:DateTime"></element>
</schema>

=== engsyst/microservices-examples/validation/src/main/resources/common-xml-examples/datetime.xml
<?xml version="1.0" encoding="UTF-8"?>
<datetime xmlns="http://it.nure.ua/xmldemo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://it.nure.ua/xmldemo datetime.xsd ">
	<Duration>P1M2D</Duration>
	<DateTime>2001-12-31T12:00:00</DateTime>
    <Time>10:00:00</Time>
	<YearMonth>2001-01</YearMonth>
	<MonthDay>--01-01</MonthDay>
	<Year>2001</Year>
	<Month>--01</Month>
<!--
    <Day>-&#45;&#45;12</Day>
    <DayOfWeek>-&#45;&#45;12</DayOfWeek>
    <DayOfWeek>-&#45;&#45;12</DayOfWeek>
    <DayOfWeek>-&#45;&#45;12</DayOfWeek>
-->

</datetime>
